### ISSUE TITLE
DOC: Improve documentation

### ISSUE THREAD

**Issue by xmnlab** [omnisci/sqlalchemy-omnisci#7]
Add more examples and explanations to the documentation.

References:
- https://sqlalchemy-ibmi.readthedocs.io/en/latest/
- https://github.com/druid-io/pydruid
- https://github.com/dropbox/PyHive#sqlalchemy
- https://github.com/aadel/sqlalchemy-solr
- https://github.com/blue-yonder/sqlalchemy_exasol
- https://github.com/preset-io/elasticsearch-dbapi/#using-sqlalchemy
- https://github.com/googleapis/python-bigquery-sqlalchemy
- https://pypi.org/project/ibm-db-sa/
- https://github.com/snowflakedb/snowflake-sqlalchemy
- https://pypi.org/project/teradatasqlalchemy/

References about integration with Apache Superset:
- https://thedataist.com/visualize-anything-with-superset-and-drill/

**Comment by tjbanks** [comment]
Great project overall! Thanks for your work!
